# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da335c9370db2586a33786ca3804c00c779b8d04ff546c72a3a82137a07333bf5193d7c7f0e900260baf1a74f24d074136770e860f67f5abbf6d2be95c9e7808

test:
  secret_key_base: f05734c38224559eee6e289c9ff4f866a54eb0789d0a0a880a5829b3eb7508a45a3a8a28fdb881d112b11448ef64c3c7735fa7ab5c80bffbce1e85096b3a1f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
